### ISSUE TITLE
UI CAN BE IMPROVED

### ISSUE THREAD

**Issue by SATVIKSH** [Sowham-3098/Tip-Calculator#1]
Some amendments can be made to the UI and Design . I can do that for the project if you assign me the work.

**Comment by sb-decoder** [comment]
Yeah Sure

**Comment by Sowham-3098** [comment]
Yeah Sure! I am assigning you.

**Comment by SATVIKSH** [comment]
A gradle file is missing from your project repo . It must not be properly updated .
I'll not be able to update the project.
